name: Collection

on:
  push:
    branches: 
    - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Docker for newma
      id: myRequest
      run: |
        docker run -v $PWD:/etc/newman -t postman/newman:latest run "./test/postman_collection_failure.json"
      continue-on-error: true
    - name: Check on failures     
      run: 
         echo ${{steps.myRequest.outcome}}
       
   
