name: Collection

on:
  push:
    branches: 
    - main

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main

    - name: Docker for newma
      id: myRequest
      run: |
         folder_path=$PWD:/etc/newman/Docker/test
         file_name=new_flow.json
         if [ -e "$folder_path/$file_name" ]; then
            echo "File exists!"
          else
            echo "File does not exist!"
            exit 1  # You can exit with a non-zero code to indicate a failure
          fi
         docker run -v $PWD:/etc/newman -t postman/newman:latest run "./test/new_flow.json"
      continue-on-error: true
    - name: Check on failures     
      run: 
         echo ${{steps.myRequest.outcome}}
       
   
