name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    # Run the POSTMAN collection
    - name: Run POSTMAN collection
      run: |
       image: postman/newman:latest
       run: newman run ./test/new_flow.json -e ./test/new_flow.json 
   
